name: Test package gdalhelpers

on:
  push

jobs:
  test:
    name: test package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install libraries
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal numpy

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run tests
        run: nosetests -verbosity=3